site_name: Garsia Case Book
site_url: https://davidgarsia0583.github.io/case-book/
theme:
  name: material

nav:
  - Home: index.md
  - Chapters:
      - Standing: chapters/01_Standing.md
      - Procida: chapters/02_Procida.md
      - Weissman: chapters/03_Weissman.md
      - Investors: chapters/04_Investors.md
      - Perkins: chapters/05_Perkins.md
      - Guarantee: chapters/06_Guarantee.md
      - Totowa: chapters/07_Totowa.md
      - Political Connections: chapters/08_Political_Connections.md
      - NJEDA & Public Funding: chapters/09_NJEDA.md
  - Exhibits:
      - Exhibit Index: exhibits/index.md
