site_name: Garsia Case Book
site_url: https://davidgarsia0583.github.io/case-book
repo_url: https://github.com/davidgarsia0583/case-book
repo_name: case-book

docs_dir: .

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
  language: en

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables

nav:
  - Home: index.md
  - Chapters:
      - Standing: chapters/01_Standing.md
      - Procida: chapters/02_Procida.md
  - Exhibits: exhibits/
